// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelter.Models;

#nullable disable

namespace Shelter.Migrations
{
    [DbContext(typeof(ShelterContext))]
    partial class ShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<bool>("Immunizations")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Breed = "Mix",
                            Gender = "Male",
                            Immunizations = true,
                            Name = "Rex",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 4,
                            Breed = "Maltese",
                            Gender = "Male",
                            Immunizations = true,
                            Name = "Snowball",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 3,
                            Breed = "Siamese",
                            Gender = "Male",
                            Immunizations = false,
                            Name = "Tyson",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 7,
                            Breed = "Pitbull",
                            Gender = "Female",
                            Immunizations = true,
                            Name = "Gilda",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 5,
                            Breed = "Poodle",
                            Gender = "Female",
                            Immunizations = true,
                            Name = "Bunny",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 10,
                            Breed = "Tuxedo",
                            Gender = "Male",
                            Immunizations = true,
                            Name = "Groucho",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 1,
                            Breed = "Lab",
                            Gender = "Male",
                            Immunizations = true,
                            Name = "Peanutbutter",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 4,
                            Breed = "Tabby",
                            Gender = "Male",
                            Immunizations = true,
                            Name = "Swiper",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 6,
                            Breed = "Hairless",
                            Gender = "Female",
                            Immunizations = true,
                            Name = "Janet",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 1,
                            Breed = "Mix",
                            Gender = "Male",
                            Immunizations = true,
                            Name = "Target",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 1,
                            Breed = "Austrailian Shepard",
                            Gender = "Female",
                            Immunizations = false,
                            Name = "TuTu",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 10,
                            Breed = "Bengal",
                            Gender = "Female",
                            Immunizations = true,
                            Name = "Cups",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
